version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  test:
    docker:
      - image: circleci/clojure:tools-deps-1.10.0.442

    working_directory: ~/conjure

    steps:
      - checkout

      - restore_cache:
          keys:
            - deps-{{ checksum "deps.edn" }}

      - run: >
          bin/kaocha
          --plugin kaocha.plugin/junit-xml
          --junit-xml-file test-results/kaocha/results.xml
          --plugin cloverage --no-cov-html --codecov

      - store_test_results:
          path: test-results

      - codecov/upload:
          file: target/coverage/codecov.json

      - save_cache:
          paths:
            - ~/.m2
          key: deps-{{ checksum "deps.edn" }}

workflows:
  version: 2
  test:
    jobs:
      - test
